services:
  db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:8.0.9
    volumes:
      - team:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']

volumes:
  team:
    external: false